# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5f2ae0c4abc59eeadb44b4041768a8c2adb631d2c49d0197dfc67c10c9c2a1ea71639f4ebe969a785c49a14799fc15fd2fecfb38f8d4cebdef93cc227328487

test:
  secret_key_base: 406bc85852fa3920bc724c99f5c576f94c14bf21f0f87868eabcc61ef7362a146ee94ccdeeacbe6b07cc65348ba5a21d8f36c5c5cbd107cc0e06cd8720eab494

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
